import { idSchema, reviewInputSchema } from "@/domain/schemas";
import { authedRoute, json, parse, readJson } from "@/server/http";
import { deleteReview, putReview } from "@/server/services/visits";
import { NextResponse } from "next/server";

/** Create or update your review. The id is generated by the client, so retries are safe. */
export const PUT = authedRoute<{ id: string }>(async ({ req, db, now, session }, params) => {
  const id = parse(idSchema, params.id);
  const input = await readJson(req, reviewInputSchema);
  const { review, created } = await putReview(db, session, id, input, now);
  return json({ review }, created ? 201 : 200);
});

/** Delete your review. Deleting one that's already gone succeeds. */
export const DELETE = authedRoute<{ id: string }>(async ({ db, session }, params) => {
  await deleteReview(db, session, parse(idSchema, params.id));
  return new NextResponse(null, { status: 204 });
});
