import { sql } from "drizzle-orm";
import {
  boolean,
  check,
  date,
  doublePrecision,
  index,
  integer,
  pgTable,
  primaryKey,
  smallint,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { AREA_KEYS } from "@/domain/areas";
import { CATEGORY_KEYS } from "@/domain/categories";
import { REACTION_KEYS } from "@/domain/reactions";

/*
 * Data rules live here as constraints, not in app code (docs/PLAN.md §7).
 * Every table has row-level security enabled with no policies: only our server, connecting as
 * the database owner, can read or write. Supabase's auto-generated API sees nothing.
 */

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const inList = (column: string, values: readonly string[]) =>
  sql.raw(`${column} in (${values.map((v) => `'${v}'`).join(", ")})`);

export const stations = pgTable(
  "stations",
  {
    /** The key reviews and check-ins point to. */
    id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
    /** Readable and stable, for links (/stations/dock-72) and the seed file. */
    slug: text("slug").notNull().unique(),
    name: text("name").notNull(),
    address: text("address").notNull(),
    neighborhood: text("neighborhood").notNull(),
    area: text("area").notNull(),
    lat: doublePrecision("lat").notNull(),
    lng: doublePrecision("lng").notNull(),
    hidden: boolean("hidden").notNull().default(false),
    createdAt: createdAt(),
  },
  (t) => [
    check("stations_area_known", inList("area", AREA_KEYS)),
    check("stations_slug_format", sql`${t.slug} ~ '^[a-z0-9]+(-[a-z0-9]+)*$'`),
  ],
).enableRLS();

export const members = pgTable(
  "members",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    name: text("name").notNull(),
    nameKey: text("name_key").notNull(),
    isOwner: boolean("is_owner").notNull().default(false),
    /**
     * A salted scrypt hash (see server/auth/passwords.ts), never the password itself: it can't be
     * turned back into the password, by anyone. Null for people who joined before passwords.
     */
    passwordHash: text("password_hash"),
    /** Wrong passwords in a row, and the lockout they trigger (slows down guessing). */
    failedLogins: smallint("failed_logins").notNull().default(0),
    lockedUntil: timestamp("locked_until", { withTimezone: true }),
    createdAt: createdAt(),
  },
  (t) => [
    uniqueIndex("members_name_key_unique").on(t.nameKey),
    // At most one owner.
    uniqueIndex("members_one_owner")
      .on(t.isOwner)
      .where(sql`${t.isOwner}`),
  ],
).enableRLS();

export const devices = pgTable(
  "devices",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    memberId: uuid("member_id")
      .notNull()
      .references(() => members.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    label: text("label").notNull().default(""),
    createdAt: createdAt(),
    lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [index("devices_member_idx").on(t.memberId)],
).enableRLS();

/** One-time links: owner-issued recovery for a forgotten password (24 h). "pair" links are no longer made. */
export const links = pgTable(
  "links",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    memberId: uuid("member_id")
      .notNull()
      .references(() => members.id, { onDelete: "cascade" }),
    tokenHash: text("token_hash").notNull().unique(),
    purpose: text("purpose").notNull(),
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    usedAt: timestamp("used_at", { withTimezone: true }),
    createdAt: createdAt(),
  },
  () => [check("links_purpose_known", inList("purpose", ["pair", "recover"]))],
).enableRLS();

const scoreColumns = Object.fromEntries(CATEGORY_KEYS.map((k) => [k, smallint(k)])) as {
  [K in (typeof CATEGORY_KEYS)[number]]: ReturnType<typeof smallint<K>>;
};

export const reviews = pgTable(
  "reviews",
  {
    /** Generated by the client so retries are idempotent. */
    id: uuid("id").primaryKey(),
    stationId: integer("station_id")
      .notNull()
      .references(() => stations.id),
    memberId: uuid("member_id")
      .notNull()
      .references(() => members.id, { onDelete: "cascade" }),
    visitedOn: date("visited_on", { mode: "string" }).notNull(),
    ...scoreColumns,
    hotTake: text("hot_take").notNull().default(""),
    body: text("body").notNull().default(""),
    tags: text("tags")
      .array()
      .notNull()
      .default(sql`'{}'::text[]`),
    createdAt: createdAt(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [
    // One review per person per station; posting again edits it.
    uniqueIndex("reviews_one_per_member_station").on(t.stationId, t.memberId),
    index("reviews_member_idx").on(t.memberId),
    check("reviews_has_a_score", sql.raw(`num_nonnulls(${CATEGORY_KEYS.join(", ")}) > 0`)),
    ...CATEGORY_KEYS.map((k) => check(`reviews_${k}_range`, sql.raw(`${k} between 1 and 5`))),
    check("reviews_hot_take_length", sql`char_length(${t.hotTake}) <= 120`),
    check("reviews_body_length", sql`char_length(${t.body}) <= 1200`),
  ],
).enableRLS();

export const checkins = pgTable(
  "checkins",
  {
    /** Generated by the client so retries are idempotent. */
    id: uuid("id").primaryKey(),
    stationId: integer("station_id")
      .notNull()
      .references(() => stations.id),
    memberId: uuid("member_id")
      .notNull()
      .references(() => members.id, { onDelete: "cascade" }),
    visitedOn: date("visited_on", { mode: "string" }).notNull(),
    note: text("note").notNull().default(""),
    createdAt: createdAt(),
  },
  (t) => [
    // One check-in per person per station per day.
    uniqueIndex("checkins_one_per_member_station_day").on(t.stationId, t.memberId, t.visitedOn),
    index("checkins_member_idx").on(t.memberId),
    check("checkins_note_length", sql`char_length(${t.note}) <= 400`),
  ],
).enableRLS();

/** One-tap reactions to a review (🔥 💯 😂 🙅). Each person can add each kind once. */
export const reactions = pgTable(
  "reactions",
  {
    reviewId: uuid("review_id")
      .notNull()
      .references(() => reviews.id, { onDelete: "cascade" }),
    memberId: uuid("member_id")
      .notNull()
      .references(() => members.id, { onDelete: "cascade" }),
    kind: text("kind").notNull(),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.reviewId, t.memberId, t.kind] }),
    check("reactions_kind_known", inList("kind", REACTION_KEYS)),
  ],
).enableRLS();
